import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { CategoryProvider } from "@/context/CategoryContext";
import { ProductProvider } from "@/context/ProductContext";
import { ToastContainer } from "react-toastify";
import { OrderProvider } from "@/context/OrderContext";
import { ClerkProvider } from "@clerk/nextjs";
import SocketProvider from "@/context/SocketProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const localization = {
  userButton: {
    action__signOut: "Гарах",
    action__manageAccount: "Тохиргоо",
  },
  signIn: {
    start: {
      title: "Нэвтрэх",
      subtitle: "Өөрийн бүртгэлээр нэвтэрнэ үү",
      actionLink: "Бүртгүүлэх",
      actionText: "Бүртгэлгүй юу?",
    },
  },
  signUp: {
    start: {
      actionLink: "Нэвтрэх",
      actionText: "Бүртгэлтэй юу?",
      subtitle: "Та доорхоос сонгон бүртгүүлнэ үү.",
      title: "Бүртгүүлэх",
    },
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider
      publishableKey={process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
      localization={localization}
    >
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <OrderProvider>
            <CategoryProvider>
              <ProductProvider>
                <SocketProvider />
                {children}
              </ProductProvider>
            </CategoryProvider>
          </OrderProvider>
          <ToastContainer
            position="top-right"
            autoClose={3000}
            hideProgressBar={false}
          />
        </body>
      </html>
    </ClerkProvider>
  );
}
